# Generated by Django 5.2.17 on 2026-09-27 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_provider', models.CharField(blank=True, max_length=20)),
                ('state_id', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WEIGHING', 'Weighing'), ('MEASURING', 'Measuring'), ('VOLUMETRIC', 'Volumetric')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('least_count', models.DecimalField(decimal_places=4, max_digits=10)),
                ('location_address', models.TextField()),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('state_id', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='traders.traderprofile')),
            ],
        ),
    ]
