# Generated by Django 5.2.17 on 2026-09-27 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=30, unique=True)),
                ('app_type', models.CharField(choices=[('NEW', 'New'), ('RENEWAL', 'Renewal'), ('RE_VERIFICATION', 'Re Verification')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('INSPECTED', 'Inspected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CERTIFIED', 'Certified')], default='SUBMITTED', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('state_id', models.CharField(max_length=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='traders.instrument')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='traders.traderprofile')),
            ],
        ),
    ]
