# Generated by Django 5.2.17 on 2026-09-27 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('traders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=30, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64)),
                ('state_id', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.application')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.instrument')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.traderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tx_id', models.CharField(max_length=255)),
                ('certificate_hash', models.CharField(max_length=64)),
                ('anchor_timestamp', models.DateTimeField()),
                ('issuer_id', models.CharField(max_length=255)),
                ('block_number', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_anchor', to='certificates.certificate')),
            ],
        ),
    ]
